name: client
description: A sample Polymer application
dependencies:
    polymer: ">=0.14.0 <0.15.0"
    core_elements: ">=0.2.0 <0.3.0"
    paper_elements: ">=0.2.0 <0.3.0"
transformers:
- polymer:
    entry_points: web/client.html
