name: drails
version: 0.1.4
author: Luis Vargas <luisvargastijerino@gmail.com>
description: DART MVC Framework inspired on Grails and Rails
homepage: https://github.com/luisvt/Drails
environment:
  sdk: '>=1.6.0'
dependencies:
#  drails_di: '^0.0.6'
#  dson: '^0.1.7'
  drails_di:
    path: ../drails_di
  dson:
    path: ../dson
  http: '>=0.11.1+1 <0.11.1+3'
  http_server: '>=0.9.3 <0.10.0'
  route: '>=0.4.6 <0.5.0'
dev_dependencies:
  test: '^0.12.0'
