name: drails
version: 0.0.2
author: Luis Vargas <luisvargastijerino@gmail.com>
description: DART MVC Framework based on Rails
homepage: https://github.com/luisvt/Drails
environment:
  sdk: 1.6.0
documentation: https://github.com/luisvt/Drails
dependencies:
  logging: any
  route: any
