name: drails
version: 0.0.9
author: Luis Vargas <luisvargastijerino@gmail.com>
description: DART MVC Framework based on Rails
homepage: https://github.com/luisvt/Drails
environment:
  sdk: '>=1.6.0'
documentation: https://github.com/luisvt/Drails
dependencies:
  http: '>=0.11.1+1 <0.12.0'
  logging: '>=0.9.2 <0.10.0'
  route: '>=0.4.6 <0.5.0'
  unittest: '>=0.10.0 <0.11.0'
