name: drails
version: 0.2.0
author: Luis Vargas <luisvargastijerino@gmail.com>
description: DART MVC Framework inspired on Grails and Rails
homepage: https://github.com/luisvt/Drails
environment:
  sdk: '>=2.0.0-dev <3.0.0'
dependencies:
  drails_di: ^0.3.0
#  drails_di:
#    path: ../drails_di
  dson: ^0.13.0
#  dson:
#    path: ../dson
  http: ^0.11.3
  http_server: ^0.9.6
  route: ^0.4.6
  logging: ^0.11.0
  path: ^1.5.1
dev_dependencies:
  build_runner: ^0.7.0
  test: ^0.12.0
