name: drails
version: 0.1.1+1
author: Luis Vargas <luisvargastijerino@gmail.com>
description: DART MVC Framework based on Grails and Rails
homepage: https://github.com/luisvt/Drails/tree/master/drails
environment:
  sdk: '>=1.6.0'
dependencies:
  drails_di: '>=0.0.1 <0.0.3'
  dson: '>=0.1.1 <0.1.4'
  http: '>=0.11.1+1 <0.12.0'
  http_server: '>=0.9.3 <0.10.0'
  route: '>=0.4.6 <0.5.0'
  unittest: '>=0.11.0+5 <0.12.0'
