name: drails
version: 0.1.2
author: Luis Vargas <luisvargastijerino@gmail.com>
description: DART MVC Framework inspired on Grails and Rails
homepage: https://github.com/luisvt/Drails
environment:
  sdk: '>=1.6.0'
dependencies:
  drails_di: '>=0.0.3 <0.0.4'
  dson: '>=0.1.4 <0.2.0'
  http: '>=0.11.1+1 <0.12.0'
  http_server: '>=0.9.3 <0.10.0'
  route: '>=0.4.6 <0.5.0'
  unittest: '>=0.11.0+5 <0.12.0'
