name: dson
version: 0.1.1
author: Luis Vargas
description: Convert Objects to Json and Json to Objects
homepage: https://github.com/luisvt/Drails/tree/master/dson
environment:
  sdk: '>=1.6.0'
dependencies:
  drails_commons:
    path: ../drails_commons
  unittest: any
