name: drails
version: 0.1.1
author: Luis Vargas <luisvargastijerino@gmail.com>
description: DART MVC Framework based on Grails and Rails
homepage: https://github.com/luisvt/Drails/drails
environment:
  sdk: '>=1.6.0'
dependencies:
  drails_di:
    path: ../drails_di
  dson:
    path: ../dson
  http: '>=0.11.1+1 <0.12.0'
  http_server: '>=0.9.3 <0.10.0'
  logging: '>=0.9.2 <0.10.0'
  route: '>=0.4.6 <0.5.0'
  unittest: '>=0.10.0 <0.11.0'
